//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardToPacketService
    {
        public int Id { get; set; }
        public Nullable<int> CardId { get; set; }
        public Nullable<int> PacketsssId { get; set; }
        public Nullable<int> ServicesssId { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Packet Packet { get; set; }
        public virtual Service Service { get; set; }
        public virtual CardToPacketService CardToPacketServices1 { get; set; }
        public virtual CardToPacketService CardToPacketService1 { get; set; }
    }
}
