//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackProject.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoming
    {
        public int Id { get; set; }
        public Nullable<long> ClientIncomes { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<System.DateTime> IncomeMonth { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
