//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FitnessEntities : DbContext
    {
        public FitnessEntities()
            : base("name=FitnessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminParol> AdminParols { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
        public virtual DbSet<CardToPacketService> CardToPacketServices { get; set; }
        public virtual DbSet<Incoming> Incomings { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<Packet> Packets { get; set; }
        public virtual DbSet<PacketToServy> PacketToServies { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<Service> Services { get; set; }
    }
}
